spring:
  application:
    name: spring-kafka-observability
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing.endpoint: "http://localhost:9411/api/v2/spans"